from homeassistant.components.sensor import SensorDeviceClass

# Writable settings fetched via POST /testdata with body "set".
# type "select": Yes/No boolean, written as 0/1.
# type "number": numeric value, written as int(round(value * 10**decimals)).
SETTINGS = {
    # Grid export controls
    69:  {
        "name": "enable_grid_export",
        "description": "Grid Export Enable",
        "type": "select",
        "hint": "Allow the inverter to export excess power back to the grid.",
    },
    70:  {
        "name": "export_limit_power",
        "description": "Grid Export Power Limit",
        "type": "number",
        "unit": "kW",
        "hint": "Maximum power the inverter is allowed to export to the grid.",
    },
    72:  {
        "name": "grid_export_delay",
        "description": "Grid Export Delay",
        "type": "number",
        "unit": "h",
        "hint": "Delay (hours) after startup before grid export is permitted.",
    },
    # Charge scheduling
    106: {
        "name": "charge_start_time",
        "description": "Charge Start Hour",
        "type": "number",
        "unit": None,  # hour-of-day (0–23), not a duration
        "hint": (
            "Preferred hour of day (0–23) to start a scheduled charge. "
            "For lithium batteries the inverter will schedule a bulk charge "
            "to begin at this hour once the battery voltage drops below the "
            "charge-enable threshold."
        ),
    },
    # State-of-charge thresholds
    153: {
        "name": "li_charge_enable_soc",
        "description": "Charge Enable SoC",
        "type": "number",
        "unit": "%",
        "hint": (
            "If battery SoC is below this level, charge-inhibit and "
            "peak-load-shave limits are overridden and the inverter will "
            "charge as fast as the source and BMS allow. "
            "Also sets the 'Low Battery' threshold for relays and alarms."
        ),
    },
    154: {
        "name": "li_charge_disable_soc",
        "description": "Charge Disable SoC",
        "type": "number",
        "unit": "%",
        "hint": (
            "If Partial Charge is on, the inverter stops charging once SoC "
            "reaches this level (relying on solar or other chargers to top up). "
            "If Charge Inhibit is on, the inverter limits import to the inhibit "
            "power until this SoC is reached. "
            "Also sets the 'Battery OK' threshold that releases low-battery relays."
        ),
    },
    155: {
        "name": "li_battery_empty_soc",
        "description": "Battery Empty SoC",
        "type": "number",
        "unit": "%",
        "hint": (
            "If SoC stays below this level for more than 5 minutes in "
            "stand-alone mode, the inverter enters Low Battery Mode and "
            "shuts down its AC output. "
            "Also sets the 'Critically Low Battery' threshold for relays and alarms."
        ),
    },
    # Charge behaviour switches
    159: {
        "name": "partial_charge_enable",
        "description": "Partial Charge Enable",
        "type": "select",
        "hint": (
            "When enabled the inverter stops grid charging once battery SoC "
            "reaches the Charge Disable SoC, leaving the remainder to solar "
            "or other chargers."
        ),
    },
    160: {
        "name": "charge_inhibit_enable",
        "description": "Charge Inhibit Enable",
        "type": "select",
        "hint": (
            "When enabled the inverter limits its grid import so that source "
            "power does not exceed the Charge Inhibit Power Limit. "
            "The limit is ignored if battery SoC drops below Charge Enable SoC."
        ),
    },
    161: {
        "name": "charge_inhibit_limit",
        "description": "Charge Inhibit Power Limit",
        "type": "number",
        "unit": "kW",
        "hint": (
            "Maximum power drawn from the grid while Charge Inhibit is active. "
            "Ignored when battery SoC is below Charge Enable SoC."
        ),
    },
    # Peak load shaving
    162: {
        "name": "peak_load_shave_enable",
        "description": "Peak Load Shave Enable",
        "type": "select",
        "hint": (
            "When enabled the inverter exports battery power to prevent "
            "source power from exceeding the Peak Load Shave Power Limit."
        ),
    },
    163: {
        "name": "peak_load_shave_limit",
        "description": "Peak Load Shave Power Limit",
        "type": "number",
        "unit": "kW",
        "hint": (
            "The inverter will discharge the battery to keep grid import "
            "below this threshold when Peak Load Shave is enabled."
        ),
    },
}

# Energy sensors integrate the corresponding power sensor (power_idx) over time.
# sign: "positive" = only count when power > 0, "negative" = only when power < 0, "all" = abs value.
#
# Battery topology: Solar Charger → DC Bus ← Battery Storage → Inverter → AC
# idx 56 (Bat Power) = total DC drawn by the inverter = solar contribution + battery storage.
# idx 88 (Solar Chg Pwr) = solar charger output into the DC bus.
# Net battery storage = idx56 - idx88:  positive → discharging from storage,
#                                        negative → net charging into storage.
# subtract_idx: subtract this power index before applying sign/accumulation.
ENERGY_SENSORS = [
    {
        "name": "grid_energy_consumed",
        "description": "Grid Energy Consumed",
        "power_idx": 29,  # External CT Power — more accurate at meter point
        "sign": "positive",
    },
    {
        "name": "grid_energy_returned",
        "description": "Grid Energy Returned",
        "power_idx": 29,
        "sign": "negative",
    },
    {
        "name": "solar_energy_produced",
        "description": "Solar Energy Produced",
        "power_idx": 88,  # Solar Chg Total Pwr
        "sign": "all",
    },
    {
        "name": "battery_energy_in",
        "description": "Battery Energy In (Charging)",
        "power_idx": 56,   # Bat Power (total DC inverter draw)
        "subtract_idx": 88,  # minus solar → net battery storage flow
        "sign": "negative",  # count when net is negative (storage charging)
    },
    {
        "name": "battery_energy_out",
        "description": "Battery Energy Out (Discharging)",
        "power_idx": 56,
        "subtract_idx": 88,
        "sign": "positive",  # count when net is positive (storage discharging)
    },
    {
        "name": "home_energy_consumed",
        "description": "Home Energy Consumed",
        "power_idx": 28,  # Load Pwr Total
        "sign": "all",
    },
]

SENSORS = {
    8: {
        "name": "system_op_mode",
        "description": "System Op. Mode",
        "type": SensorDeviceClass.ENUM,
        "options": [
            "System Off",
            "Standby",
            "Startup",
            "Full Auto",
            "Stand Alone",
            "Grid Tied",
            "GT to SA Trans",
            "Auto Src Only",
            "Auto Restart Mode",
            "Low Bat Mode",
            "Shutdown",
            "Tripped",
            "Trip Pending",
            "Man Inv Only",
            "Man Src Only",
            "IO Test Mode",
            "PWM Stand Alone Test",
            "PWM Tracking Test",
            "Demand Response Test",
        ],
    },
    9: {
        "name": "system_status",
        "description": "System Status",
        "type": SensorDeviceClass.ENUM,
        "options": [
            "Event Queue Empty",
            "",
            "Eventlog Initialized",
            "No Recent Events",
            "Event Qu Flushed",
            "Waiting",
            "System Busy",
            "System Initialize",
            "Fault Reset",
            "Switched Off",
            "Emergency Stop",
            "Remote Off",
            "Src Disconnect Req",
            "Generator Started",
            "Generator Stopped",
            "Summations Cleared",
            "Settings Saved",
            "Settings Resored",
            "Settings Reset",
            "Faults Masked",
            "Auto Fault Reset",
            "uProcessor Reset",
            "System Off",
            "Standby",
            "Startup",
            "Full Auto",
            "System Off Grid",
            "System Grid Tied",
            "Auto Src Only",
            "Shutdown",
            "System Tripped",
            "Manual Inv Only",
            "Manual Src Only",
            "IO Test Mode",
            "PWM Stand Alone Test",
            "PWM Tracking Test",
            "Demand Response Test",
            "Auto-restart on grid",
            "Prep Stand-Alone Req",
            "Inv Only Mode Req",
            "Src CB 1 Closed",
            "Src CB 1 Opened",
            "Src CB 2 Closed",
            "Src CB 2 Opened",
            "Inv CB Closed",
            "Inv CB Opened",
            "PE Relay Closed",
            "PE Relay Opened",
            "Ext CB Closed",
            "Ext CB Opened",
            "Low Export Power",
            "Export Limit Active",
            "Src Supply Detected",
            "Src Ok Cnt Down Busy",
            "Busy Saving Trip Log",
            "Gen Output Detected",
            "Detecting Gen Supply",
            "Equalize Enable",
            "Equalize Disable",
            "Src Low V Mag T4",
            "Src High V Mag T4",
            "Low Battery Mode",
            "Auto Restart Mode",
            "Inverter Masked",
            "Partial Fault Reset",
            "Start Chg - LowBattV",
            "Start Maint. Chg",
            "Start Scheduled Chg",
            "User Requested Chg",
            "Bulk-CC Chg",
            "Abs-CV Chg",
            "Top-off Chg",
            "Chg Cycle Complete",
            "Equalise Chg",
            "Equ Abs Chg",
            "Tapering to Float V",
            "Float Chg",
            "Pre-Con Chg",
            "Top-up Chg",
            "Top-off Chg End dA",
            "Chg Ended by RBC",
            "Bat Cycling Started",
            "Bat Cycling Complete",
            "BMU Ctrl Chg",
            "Auton Dis/Chg",
            "Auton Dis/Chg End",
            "Battery Recon Low V",
            "TZ Prim High Amps",
            "TZ Bat Low Volts",
            "TZ Bat High Volts",
            "TZ Inv High Amps",
            "PWM1 Shutdown",
            "PWM2 Shutdown",
            "Src Low Freq",
            "Src High Freq",
            "Src Low Volts",
            "Src High Volts",
            "Src Under Freq Stg2",
            "Src Over Freq Stg2",
            "Src Under Volts Stg3",
            "Src Under Volts Stg2",
            "Src Over Volts Stg2",
            "Src Over Volts Stg3",
            "Src Vector Shift",
            "Src RoCoF",
            "Src V Step Change",
            "Src F Step Change",
            "Src Low Volts Mag",
            "Src High Volts Mag",
            "Inv Low Freq",
            "Inv High Freq",
            "Inv Low Volts",
            "Inv High Volts",
            "Inv Low Volts Mag",
            "Inv High Volts Mag",
            "Inv Short Circuit",
            "Inv Overload",
            "High Xfmr Temp",
            "High HeatSink Temp",
            "High Inductor Temp",
            "Xfmr Temp  Fail",
            "Heatsink Temp Fail",
            "Inductor Temp Fail",
            "Thermal Trip",
            "EEPROM Fail",
            "Real Time Clock Fail",
            "Corrupt User Setting",
            "Corrupt Sys Setting",
            "No System Master",
            "Multiple Masters",
            "Phase Config Err",
            "Firmware Mismatch",
            "Dev Type Mismatch",
            "Master Mismatch",
            "Par Device Start Req",
            "Par Dev Grid-Con Req",
            "Par Dev Comms Check",
            "Par Dev Sync Check",
            "Dar Dev Close Relays",
            "Par Device Start",
            "Par Device Flt",
            "Par Device Not Ready",
            "Par Device Comms Flt",
            "Par Sync Freq Flt",
            "Par Sync Mag Flt",
            "No Sync Pulse",
            "Par Sync Trip Req",
            "Par Sync Low Freq",
            "Par Sync High Freq",
            "Par Sync Low Volts",
            "Par Sync High Volts",
            "Spur V on Load Port",
            "Spur V on Src CB2",
            "SrcCB1 Fail to Close",
            "SrcCB1 Fail to Open",
            "SrcCB1 Spur Close",
            "SrcCB1 Spur Open",
            "SrcCB2 Fail to Close",
            "SrcCB2 Fail to Open",
            "SrcCB2 Spur Close",
            "SrcCB2 Spur Open",
            "Inv Relay Closed",
            "Inv CB Fail to Close",
            "Inv CB Fail to Open",
            "Inv CB Spur Close",
            "Inv CB Spur Open",
            "Ext CB Fail to Close",
            "Ext CB Fail to Open",
            "Ext CB Spur Close",
            "Ext CB Spur Open",
            "Source Relay Fault",
            "5V Power Supply Fail",
            "Flt FETs Inv",
            "Sync Flt",
            "Grid Phase Rotation",
            "DC Bus Volts Trip",
            "High Bat Current",
            "High Primary Current",
            "DC Bus V Crit High",
            "DC Bus V Crit Low",
            "DC Bus High Volts",
            "DC Bus Low Volts",
            "Island Detected",
            "Generator On Flag",
            "Generator FB Fail",
            "Generator Low Load",
            "Max Exp Reached",
            "Exp Lim - High Temp",
            "Exp Lim - Low Dc V",
            "Exp Lim - Low Load",
            "Exp Lim - High Vrms",
            "Aux Relay 1 Engaged",
            "Aux Relay 2 Engaged",
            "High Bat Volts",
            "Low Bat Volts",
            "Bat Reconnect Volts",
            "Bulk Chg Pending",
            "Low Bat SoC",
            "Test Mode Req Block",
            "Reboot Blocked",
            "Reboot Request",
            "Rem Cntrl Comms T/O",
            "Invalid Bat Setting",
            "Invalid Bat State",
            "Invalid Bat Mode",
            "Max Chg Amps OL",
            "Crit High Chg Amps",
            "Crit High Dis Amps",
            "CAN Trip Request",
            "CAN Stand-Alone Req",
            "Bat Critical Alarm",
            "Bat Low Alarm",
            "High Load (Relay 1)",
            "High Load (Relay 2)",
            "Freq Shift Active",
            "BMSa_Comms Timeout",
            "BMSw_Comms Timeout",
            "BMS Invalid SoC Msg",
            "BMS Invalid Trgt Msg",
            "BMSa_General",
            "BMSa_Bat High Volts",
            "BMSa_Bat Low Volts",
            "BMSa_Bat High Temp",
            "BMSa_Bat Low Temp",
            "BMSa_BattHighTempChg",
            "BMSa_BattLowTempChg",
            "BMSa_Bat High Amps",
            "BMSa_BattHighAmpsChg",
            "BMSa_Contactor Fault",
            "BMSa_Bat Short Cct",
            "BMSa_BMS internal",
            "BMSa_Cell Imbalance",
            "BMSw_General",
            "BMSw_Bat High Volts",
            "BMSw_Bat Low Volts",
            "BMSw_Bat High Temp",
            "BMSw_Bat Low Temp",
            "BMSw_BattHighTempChg",
            "BMSw_BattLowTempChg",
            "BMSw_Bat High Amps",
            "BMSw_BattHighAmpsChg",
            "BMSw_Contactor Fault",
            "BMSw_Bat Short Cct",
            "BMSw_BMS internal",
            "BMSw_Cell Imbalance",
            "rsvd",
            "rsvd",
            "Gen StopStart Masked",
            "CAN Bus Off",
            "No Phs Master",
        ],
    },
    22: {
        "name": "battery_mode",
        "description": "Battery Mode",
        "type": SensorDeviceClass.ENUM,
        "options": [
            "System Off",
            "Standby",
            "Startup",
            "Full Auto",
            "Stand Alone",
            "Grid Tied",
            "GT to SA Trans",
            "Auto Src Only",
            "Auto Restart Mode",
            "Low Bat Mode",
            "Shutdown",
            "Tripped",
            "Trip Pending",
            "Man Inv Only",
            "Man Src Only",
            "IO Test Mode",
            "PWM Stand Alone Test",
            "PWM Tracking Test",
            "Demand Response Test",
        ],
    },
    26: {
        "name": "grid_power",
        "description": "Grid Power",
        "type": SensorDeviceClass.POWER,
    },
    27: {
        "name": "inverter_power",
        "description": "Inverter Power",
        "type": SensorDeviceClass.POWER,
    },
    28: {
        "name": "load_power",
        "description": "Load Power",
        "type": SensorDeviceClass.POWER,
    },
    29: {
        "name": "external_ct_power",
        "description": "External CT Power",
        "type": SensorDeviceClass.POWER,
    },
    42: {
        "name": "grid_voltage_rms",
        "description": "Grid Voltage RMS",
        "type": SensorDeviceClass.VOLTAGE,
    },
    43: {
        "name": "check_grid_voltage_rms",
        "description": "Check Grid Voltage RMS",
        "type": SensorDeviceClass.VOLTAGE,
    },
    44: {
        "name": "inverter_voltage_rms",
        "description": "Inverter Voltage RMS",
        "type": SensorDeviceClass.VOLTAGE,
    },
    45: {
        "name": "load_voltage_rms",
        "description": "Load Voltage RMS",
        "type": SensorDeviceClass.VOLTAGE,
    },
    46: {
        "name": "external_voltage_rms",
        "description": "External Voltage RMS",
        "type": SensorDeviceClass.VOLTAGE,
    },
    47: {
        "name": "grid_current",
        "description": "Grid Current",
        "type": SensorDeviceClass.CURRENT,
    },
    48: {
        "name": "inverter_current",
        "description": "Inveter Current",
        "type": SensorDeviceClass.CURRENT,
    },
    49: {
        "name": "inverter_primary_current",
        "description": "Inverter Primary Current",
        "type": SensorDeviceClass.CURRENT,
    },
    50: {
        "name": "load_current",
        "description": "Load Current",
        "type": SensorDeviceClass.CURRENT,
    },
    51: {
        "name": "external_current",
        "description": "External Current",
        "type": SensorDeviceClass.CURRENT,
    },
    56: {
        "name": "battery_power",
        "description": "Battery Power",
        "type": SensorDeviceClass.POWER,
    },
    57: {
        "name": "battery_voltage",
        "description": "Battery Voltage",
        "type": SensorDeviceClass.VOLTAGE,
    },
    58: {
        "name": "battery_current",
        "description": "Battery Current",
        "type": SensorDeviceClass.CURRENT,
    },
    88: {
        "name": "solar_charge_power_total",
        "description": "Solar Charge Power Total",
        "type": SensorDeviceClass.POWER,
    },
    89: {
        "name": "solar_charge_amps_total",
        "description": "Solar Charge Amps Total",
        "type": SensorDeviceClass.CURRENT,
    },
    118: {
        "name": "source_relay_status",
        "description": "Source Relay Status",
        "type": SensorDeviceClass.ENUM,
        "options": [
            "CB Open",
            "CB Closed Not ACK",
            "CB Closed",
            "CB Open Not ACK",
            "CB Faulty",
        ],
    },
    139: {
        "name": "battery_soc",
        "description": "Battery State of Charge",
        "type": SensorDeviceClass.BATTERY,
    },
    143: {
        "name": "battery_temperature",
        "description": "Battery Temperature",
        "type": SensorDeviceClass.TEMPERATURE,
    },
}
